### ISSUE TITLE
Write results to txt

### ISSUE THREAD

**Issue by AidanWelch** [AidanWelch/DeCode#2]
This should be simple, write the results of the SortChars in a mannerly, easy to read order

**Comment by badcodecat** [comment]
I can help with this. If you want I can help with several other things I noticed in your code (Recursion in FindFile to a loop, etc).

**Comment by AidanWelch** [comment]
Yeah, I would love it, I'll add you as a contributor.

**Comment by badcodecat** [comment]
I would like to contact you more about this project, I'm actually a bit confused as to what it does
I also would like to know of any specific format you would like for writing the results.

**Comment by AidanWelch** [comment]
You can contact me at aidansw@yahoo.com, but what would you like to know?

**Comment by badcodecat** [comment]
Can the output be a json? I can do the txt but json format might be good.
For example:
```
{
"A": 7.6,
"B": 20.5,
"!": 64.88
}
```
Please let me know what you think

**Comment by AidanWelch** [comment]
Yeah, perhaps optional, also since  I am going to add XML integration anyway we could have optional txt, xml, or json output
